### ISSUE TITLE
default branch in new git repo should be `main` not `master`

### ISSUE THREAD

**Issue by eioe** [SHEscher/scilaunch#1]
# Problem:
when scilaunch initializes a new git repo for me, it sets the default branch to `master` which is not SOTA according to the standards followed by many [platforms these days](https://sfconservancy.org/news/2020/jun/23/gitbranchname/) (e.g., [GitHub](https://github.com/github/renaming)). 

# Suggested fix:
The most prominent alternative is using the name `main` instead. I suggest, to directly rename the default branch from `master` to `main` on initialization.

**Comment by SHEscher** [comment]
I updated the [`research-project`](https://github.com/SHEscher/research-project/tree/main) template in this [commit](https://github.com/SHEscher/research-project/commit/f45bf2a5c80e132e4de6356c2c7293e3c4a15553), such that all git users have the branch set to `main` independent of their version.

However, you can change the global `git` configs yourself:

```shell
git config --global init.defaultBranch main
``` 

See this [post](https://superuser.com/questions/1419613/change-git-init-default-branch-name)
